### ISSUE TITLE
D7

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-imu#1]
Brilliant code, hardware and instructions. Got up in no time! Please note the instructions in readme.md reads int pin to D7, while the code says 8

**Comment by rob42** [comment]
Mine is on D7. Where do you see it in the code?

**Comment by joabakk** [comment]
Oh I thought that was https://github.com/SignalK/signalk-imu/blob/master/EM7180_MPU9250_BMP280_M24512DFC_IMU/Globals.h#L390

**Comment by rob42** [comment]
Mostly the code is Kris Winers, that var doesnt seem to be used. Maybe a leftover from arduino origins.
Closing
